# This workflow mirrors the repository to GitLab.
# It is triggered on push, delete, and on a daily schedule.
# This ensures that the GitLab repository is always up-to-date.
name: Mirror to GitLab

on:
  push:
    branches: [main, master, develop]
  delete:
  schedule:
    - cron: '0 0 * * *'  # Daily sync as backup

# Concurrency control ensures that only one instance of this workflow runs at a time for the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # The 'gitlab-mirror' job performs the mirroring.
  gitlab-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This action handles the mirroring to GitLab using an SSH key.
      # It is more secure than using a personal access token in the URL.
      - name: Mirror to GitLab
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/${{ github.repository }}.git"
          destination-repo: "git@gitlab.com:daryllundy/gitlab-dashwatch.git"

      # This step checks the exit code of the previous step to determine if the mirror was successful.
      - name: GitLab Mirror Status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Successfully mirrored to GitLab"
          else
            echo "❌ GitLab mirror failed"
            exit 1
          fi
